### ISSUE TITLE
Trouble adding new modules

### ISSUE THREAD

**Issue by joannagould** [eyebeam/eyebeam.org#11]
Trying to add [new modules here](https://staging.eyebeam.org/education/) - did 1 successfully - but take about 3 mins to load then times out to this:
<img width="1360" alt="screen shot 2018-03-05 at 1 55 32 pm" src="https://user-images.githubusercontent.com/37080849/36993786-01b6318a-207d-11e8-9662-5a64cf9b8f63.png">

**Comment by dphiffer** [comment]
Ugh, I really hope the new database server clears this up. I dunno if you wanna try again tonight after the migration is finished?

**Comment by joannagould** [comment]
I'll try later! Probably tomorrow morning at this stage.

**Comment by dphiffer** [comment]
It seems like the server migration has made a lot of things work better. I'm gonna close this, assuming it was related to the old slow performance.
