### ISSUE TITLE
Missing links for Residents

### ISSUE THREAD

**Issue by joannagould** [eyebeam/eyebeam.org#12]
In old website we could have the residents link somewhere - like to their personal website or more information about them on our website. Wordpress panel like this on old site:

<img width="844" alt="screen shot 2018-03-06 at 9 16 04 am" src="https://user-images.githubusercontent.com/37080849/37037001-56b2997e-211f-11e8-8783-40c7376c185d.png">

New Wordpress panel:

<img width="974" alt="screen shot 2018-03-06 at 9 16 09 am" src="https://user-images.githubusercontent.com/37080849/37037007-5960702e-211f-11e8-9271-eb79ce3567c5.png">

And when I click 'Preview Changes' button on the new site it goes here:

<img width="1032" alt="screen shot 2018-03-06 at 9 16 20 am" src="https://user-images.githubusercontent.com/37080849/37036996-5410db2c-211f-11e8-8f8c-21b6b5f8706e.png">

**Comment by dphiffer** [comment]
Two different things here:
- We need additional fields for residents (at _least_ links & email address)
- Resident posts are a kind of content that only exist as content on other pages, so it isn't really capable of being "previewed."

**Comment by dphiffer** [comment]
(The email address required so we can let residents update their own profiles.)

**Comment by joannagould** [comment]
Additional fields would be great of email and link would be great!

**Comment by madpenny** [comment]
Any word on this?

**Comment by dphiffer** [comment]
Added some new fields, and migrated the links from the old site.

<img width="811" alt="screen shot 2018-03-10 at 9 21 08 pm" src="https://user-images.githubusercontent.com/38114/37248825-fe324b54-24a8-11e8-8073-bae5b5fc0ffe.png">
