### ISSUE TITLE
Contents Page - education page

### ISSUE THREAD

**Issue by joannagould** [eyebeam/eyebeam.org#13]
I can't make the contents page on the [Education page](https://staging.eyebeam.org/education/) link to the correct parts. This isn't essential for the launch. I'm going to probably remove it we can reinstate it later.

**Comment by dphiffer** [comment]
I think it's just the first item, no? It might have to do with the TOC title override, or maybe the hyphen in "Techno-logy"? Either way it looks like a bug to me.

**Comment by joannagould** [comment]
I've removed this for now - let's re-visit after the launch
