### ISSUE TITLE
GLITCH : Related Readings 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#132]
The "related readings" posts on the site are glitching, I would say remove the feature at all.
<img width="1710" alt="Screen Shot 2020-08-05 at 10 38 25 AM" src="https://user-images.githubusercontent.com/31375201/89427131-e7fc4000-d708-11ea-9953-8559443baf0c.png">

**Comment by emmalevesque** [comment]
Reolved with [this commit](https://github.com/eyebeam/eyebeam.org/commit/13f7634839bc4cad2ab20ef817f01cc6a46805ff)

**Comment by emmalevesque** [comment]
Resolved with 13f7634
