### ISSUE TITLE
search function

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#142]
just curious why there are percentage signs, J. asked about it!
<img width="1016" alt="Screen Shot 2020-10-28 at 11 23 52 AM" src="https://user-images.githubusercontent.com/31375201/97459076-bebb0c80-1911-11eb-991f-8487c9d6f80a.png">

**Comment by emmalevesque** [comment]
That appears to be an error, looks like there's a style issue on the search page now. I'm fixing this now and updating the production site.
