### ISSUE TITLE
Event page loading

### ISSUE THREAD

**Issue by joannagould** [eyebeam/eyebeam.org#15]
Event page loading has gone odd. I understand if the lazy-load can't be ready. But the image grid returning to normal would be great.
<img width="901" alt="screen shot 2018-03-06 at 4 21 00 pm" src="https://user-images.githubusercontent.com/37080849/37059066-663972e2-215a-11e8-92ad-1bed95653848.png">

**Comment by dphiffer** [comment]
Ah, I know why it does this. Fix coming up.

**Comment by dphiffer** [comment]
Fixed!
