### ISSUE TITLE
Accessible Colors 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#17]
Hi, could you change the greenish accent color to something more accessible. WCAG 2.0 level AA requires a contrast ratio of at least 4.5:1 for normal text and 3:1 for large text. Level AAA requires a contrast ratio of at least 7:1 for normal text and 4.5:1 for large text. Here's a contrast checker: https://webaim.org/resources/contrastchecker/

**Comment by dphiffer** [comment]
Yes! I am in favor of making our colors more accessible. Also cc @leigler in case he has any thoughts/feelings.

See also: #10 #14

**Comment by leigler** [comment]
Inline w/ this I'd also suggest changing the mailing list form's inner text from gray to white

**Comment by leigler** [comment]
I think we can stick with the Large Text ratios for green.

_Updated Green:_ 
- #46A07F (WCAG AA PASS)
- #3A8368 (WCAG AAA PASS)

I also checked the other two colors (red and blue):

_Red:_ 
- Fine as is for WCAG AA
- #E22F22 (WCAG AAA PASS)

_Blue:_
- #009CCC (WCAG AA PASS)
- #007DA3 (WCAG AAA PASS)

**Comment by madpenny** [comment]
Hey this looks good, thank you

**Comment by dphiffer** [comment]
Done! Thanks all.
