### ISSUE TITLE
Add CapitalOne logo to Education page as a funder

### ISSUE THREAD

**Issue by poohlaga** [eyebeam/eyebeam.org#20]
CapitalOne is one of the biggest supporters for the education program so we'll need to represent their support on the bottom of the Education page (https://www.eyebeam.org/education/). If not the footer, we can place it at the bottom of the page itself.
logo to use:
![capitalone-white-shadow](https://user-images.githubusercontent.com/2982181/37107740-307bf4d2-2203-11e8-855b-58da5f1ce1b7.png)

**Comment by poohlaga** [comment]
Logo w/ color if on a white background
![2000px-capital_one_logo svg](https://user-images.githubusercontent.com/2982181/37107863-71a6e6f6-2203-11e8-90b8-dcf8d5b97021.png)

**Comment by dphiffer** [comment]
I can help with this, @poohlaga! Do we have text that will accompany this, like on the [Residency page](https://www.eyebeam.org/residency/)? Or just the logo by itself? Should it link out to CapitalOne?

**Comment by poohlaga** [comment]
Thanks!!!  We only need the text "Eyebeam would like to thank and acknowledge the support from the following funders of our education programs." 
And the logo from Cap One & NYSCA (sorry, forgot them) 
No need for linking

**Comment by dphiffer** [comment]
Done! Let me know if the treatment needs any adjusting.

**Comment by poohlaga** [comment]
Looks great, thanks!!!
ᐧ
