### ISSUE TITLE
Uploading Photos 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#22]
Just tried to upload a new photo and got this message. Not sure what it means 
<img width="1191" alt="screenshot 2018-03-08 13 40 14" src="https://user-images.githubusercontent.com/31375201/37169784-eb0123ee-22d6-11e8-8057-9beab41d3636.png">

**Comment by dphiffer** [comment]
Oof, that is weird. Lemme see if I can replicate it.

**Comment by dphiffer** [comment]
Is it repeatable for you? I wasn't able to recreate the issue. Also, what URL are you seeing that error on?

**Comment by dphiffer** [comment]
One other thing to try is to see if it's specific to the file you were trying to upload.

**Comment by madpenny** [comment]
I just tried it again, any image file I try to upload through media gives me the error message. Here's the URL: https://www.eyebeam.org/wp-admin/media-new.php

**Comment by dphiffer** [comment]
One more question, @madpenny, does this also happen here?
https://staging.eyebeam.org/wp-admin/media-new.php

Still haven't been able to reproduce this one.

**Comment by madpenny** [comment]
@dphiffer I just looked into it. Some images uploaded, others said "http" error. Tried it again on the main site that with the image that uploaded successfully to staging site and agian.."http" error.

**Comment by madpenny** [comment]
It's working now? I'm really not sure what the problem was...

**Comment by dphiffer** [comment]
@madpenny I think there still might be a real issue here, related to something called WP_Cron. I see a bunch of errors logged that say "premature end of script headers," which lead me to [this forum thread](https://discussion.dreamhost.com/t/real-cron-job-causing-premature-end-of-script-headers/59179/4). If you see this again, I think we should open a support ticket with Dreamhost and see if we can sort it out.

**Comment by dphiffer** [comment]
For future reference, here's an example of the errors I'm seeing:

```
[Sun Mar 11 03:55:29 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520765607.7322189807891845703125
[Sun Mar 11 08:20:55 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520781534.1841630935668945312500
[Sun Mar 11 13:31:56 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520800194.7256350517272949218750
[Sun Mar 11 17:48:32 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520815591.3461000919342041015625
[Mon Mar 12 02:03:11 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520845269.1802780628204345703125
[Mon Mar 12 05:18:26 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520856985.1644170284271240234375
[Mon Mar 12 07:45:39 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: http://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520865818.3348820209503173828125
[Mon Mar 12 08:48:29 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520869587.2430109977722167968750
[Mon Mar 12 08:52:26 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520869825.1369230747222900390625
[Mon Mar 12 12:46:46 2018] [error] [client 172.68.174.80] Premature end of script headers: wp-cron.php, referer: https://staging.eyebeam.org/wp-cron.php?doing_wp_cron=1520883884.5745110511779785156250
```

**Comment by dphiffer** [comment]
Gonna guess that `172.68.174.80` is the Eyebeam IP address. (You can check at whatismyip.com)

**Comment by madpenny** [comment]
It's happening again. I've filed a ticket with Dreamhost. Will keep you updated.

**Comment by madpenny** [comment]
It's working, this is what Dreamhost had to say:
It looks like your /tmp partition is nearly full (97%) which can lead to
the trouble you're reporting. By default, the /tmp partition is sized
right for most users. It looks like you need more space, though. I've set
/tmp to use the full disk space available to you. Please try your image
uploads now and let us know if you're still running into any errors.
