### ISSUE TITLE
Resident Links 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#26]
Hey- this isn't high priority- but is there any way that you could link the name of the resident and image to their introduction or bio without having the link below? I want to thank you for the work you did adding the links, but we decided it would be better if you could link the name and image.

https://www.eyebeam.org/residency/ 
![screen shot 2018-03-12 at 12 45 29 pm](https://user-images.githubusercontent.com/31375201/37297225-86d3fa52-25f3-11e8-9270-2ac79117da22.png)

**Comment by dphiffer** [comment]
Yes, linking the name/photo seems like a good idea.

- I've made the link inputs support multiple links, the name/photo will choose the first link.
- In the case of a collaborative group, the code will assume that the first link is for the collaboration and not a single team member (this is currently _not_ the case for Joanne McNeil and my collaboration on OurNet)

There are some related issues around collaborations that we should probably discuss more at some point. For now I'll go ahead and link the name/photo.

**Comment by dphiffer** [comment]
If it's preferred, I can still bring back the WYSIWYG names editor, which offers a way to selectively add links to the names. This would replace the list-of-links inputs, at least until we introduce the user-editable functionality.

**Comment by madpenny** [comment]
@dphiffer Is the link input currently working with the photo/name?  I think having a WYSIWYG is a good idea for now. As far as collaborative project perhaps we can just link to a blog post that explains the artist, their collaborative project & leads to other links which refer users to the individual artists work as well (does that make sense?)

**Comment by madpenny** [comment]
Thanks! This looks good.

**Comment by dphiffer** [comment]
Yeah, I think the list-of-links method makes more sense in light of a future capacity for alumni to edit their info.
