### ISSUE TITLE
People Page Drop Down 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#27]
Can you add an "all" section in the resident year drop-down? 
https://www.eyebeam.org/people/
![screen shot 2018-03-12 at 12 48 28 pm](https://user-images.githubusercontent.com/31375201/37297394-f95fe680-25f3-11e8-9b2d-cd6b1f59f952.png)

**Comment by dphiffer** [comment]
Yep, will do.

**Comment by dphiffer** [comment]
Done!
