### ISSUE TITLE
Lazy Load Glitch 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#28]
On the lazy load pages there is a glitch that makes the webpage inch upwards by itself. I attached a screen recording zip. This happens on /ideas /events. 

[lazy load glitch.zip](https://github.com/eyebeam/eyebeam.org/files/1803809/lazy.load.glitch.zip)

**Comment by dphiffer** [comment]
Weird, this seems Chrome-specific. I'll look into it.

**Comment by dphiffer** [comment]
Fixed!
