### ISSUE TITLE
Education Page Module Glitch 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#35]
On https://www.eyebeam.org/education/ the module' display in a strange way as you scroll down. 
![screen shot 2018-03-13 at 1 57 02 pm](https://user-images.githubusercontent.com/31375201/37360510-e180b5a2-26c6-11e8-9336-b30b6c5ac9c8.png)

**Comment by madpenny** [comment]
This happens on /about too

**Comment by dphiffer** [comment]
This should be fixed!
