### ISSUE TITLE
About Page TOC Glitch 

### ISSUE THREAD

**Issue by madpenny** [eyebeam/eyebeam.org#36]
@dphiffer On https://www.eyebeam.org/about/ the TOC is not linking and even though the modules are made to take 1/2 the page there are strange breaks 
![screen shot 2018-03-15 at 1 23 36 pm](https://user-images.githubusercontent.com/31375201/37479974-64381808-2854-11e8-8ab3-c9ae67ca0866.png)
![screen shot 2018-03-15 at 1 23 28 pm](https://user-images.githubusercontent.com/31375201/37479975-6448138e-2854-11e8-8e42-06a5d716b5b5.png)

**Comment by dphiffer** [comment]
I think this is fixed now, but let me know if you see it crop up again.
