### ISSUE TITLE
Donate page testing

### ISSUE THREAD

**Issue by dphiffer** [eyebeam/eyebeam.org#6]
Okay, the donate page is pretty much working now, for some minimal definition of "working."
http://staging.eyebeam.org/donate/

I presently have it in "testing" mode, which means it will *only* work with [Stripe's test credit cards](https://stripe.com/docs/testing#cards).

Basically you should be able to make a donation of any amount (weirdly, though, it rejected my attempt at a $1 donation, who knows...) with the following:

* Number: `4242 4242 4242 4242`
* Expiration: `11/20` (I think this is arbitrary)
* CVC: `111` (also arbitrary)
* Zip: `11111` (this too, also arbitrary)

Remaining issues:
* [x] Disable the form while the submission is still loading (re-enable it on error)
* [x] Come up with better feedback on success/error? Open to suggestions.
* [x] Hide the form when the donation is successful. What should they see at this point?
* [x] Send an email to somebody (what address?) upon success (also on error? could be helpful or annoying.)
* [x] Test that it actually works in "live mode."
* [x] Stretch goal: auto-subscribe to the "donors" list in Mailchimp

**Comment by joannagould** [comment]
Looking good. Re your questions **In bold** below: 

- Disable the form while the submission is still loading (re-enable it on error) - **Sounds good**
- Come up with better feedback on success/error? Open to suggestions. - **Like if this payment does/does not go through? I might in the meantime edit the text to reflect 'Contact XX@eyebeam.org if you have any problems'**
- Hide the form when the donation is successful. What should they see at this point? '**Just a 'Thanks for your donation - visit Eyebeam here' with a link to the events page or home page**
- Send an email to somebody (what address?) upon success (also on error? could be helpful or annoying.) - **I think Stripe has this functionality - let me look into it. They will also get a 'thank you' email from us later**
-  Test that it actually works in "live mode." **agreed**
-  Stretch goal: auto-subscribe to the "donors" list in Mailchimp **agreed**

**Comment by dphiffer** [comment]
For now I will assume `xx@eyebeam.org` is `info@eyebeam.org` but I can change that later.

**Comment by joannagould** [comment]
Which API key did you use? There are two - one that links to Salesforce and one that doesn't. Can you check it's the 'Eyebeam Salesforce Donations' option?

<img width="1406" alt="screen shot 2018-03-05 at 12 41 51 pm" src="https://user-images.githubusercontent.com/37080849/36990422-ae42f646-2072-11e8-918d-83d841df6985.png">

**Comment by dphiffer** [comment]
I had `eyebeam.org` selected! Thanks for the heads up. This is fixed now.

**Comment by joannagould** [comment]
Perfect thanks! Sorry for not communicating that better earlier. And yes info@eyebeam.org is best!

**Comment by dphiffer** [comment]
Ok, all done with this one.

@joannagould, the one remaining question is that the Mailchimp Donors list seems to have "full names" in the "first name" column I'm using. So the data I'm adding is inconsistent with what came before.
