### ISSUE TITLE
Footer Address

### ISSUE THREAD

**Issue by leigler** [eyebeam/eyebeam.org#8]
Currently trying to highlight the address (199 Cook St) also highlights odd parts of the footer (icons, etc). 
While usually this isn't a problem, I imagine some people will want to highlight the address to look up on maps.google , etc (esp on mobile)

**Comment by dphiffer** [comment]
Yeah that seems like a bad UX behavior as it stands now. I'll try wrapping the content in `<p>` tags and see if that helps.

**Comment by dphiffer** [comment]
This was fixed a while back. It had to do with unwanted `width` CSS attributes.
