### ISSUE TITLE
complex subpages (education & about) submenu

### ISSUE THREAD

**Issue by leigler** [eyebeam/eyebeam.org#9]
- Ideally the full bar sub-menu should only appear after the inline menu is scrolled passed
- The submenu should also remain fixed under the menu page.

**Comment by joannagould** [comment]
I just realize this might be linked to my new issues #13

**Comment by dphiffer** [comment]
Makes sense, I'll add that behavior.

**Comment by dphiffer** [comment]
Fixed!
